/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: RoundTrip.c
  Source: RoundTrip.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#include "RoundTrip.h"

static const uint32_t RoundTripModule_DataType_ops [] =
{
  /* DataType */
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (RoundTripModule_DataType, payload),
  DDS_OP_RTS
};

const dds_topic_descriptor_t RoundTripModule_DataType_desc =
{
  .m_size = sizeof (RoundTripModule_DataType),
  .m_align = sizeof (char *),
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE,
  .m_nkeys = 0u,
  .m_typename = "RoundTripModule::DataType",
  .m_keys = NULL,
  .m_nops = 2,
  .m_ops = RoundTripModule_DataType_ops,
  .m_meta = ""
};

