/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Throughput.c
  Source: Throughput.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#include "Throughput.h"

static const uint32_t ThroughputModule_DataType_ops [] =
{
  /* DataType */
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (ThroughputModule_DataType, count),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (ThroughputModule_DataType, payload),
  DDS_OP_RTS
};

const dds_topic_descriptor_t ThroughputModule_DataType_desc =
{
  .m_size = sizeof (ThroughputModule_DataType),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE,
  .m_nkeys = 0u,
  .m_typename = "ThroughputModule::DataType",
  .m_keys = NULL,
  .m_nops = 3,
  .m_ops = ThroughputModule_DataType_ops,
  .m_meta = ""
};

